### ISSUE TITLE
Error when building document - highlights

### ISSUE THREAD

**Issue by stevejpurves** [myst-templates/cageo#1]
This template builds a pdf successfully but with non fatal errors.

This template has a "highlights" section, currently specified as a part in the document. The description says that the part content should be in the form of a bullet point list. However, when an author does that the following error occurs

```
./paper.tex:154: LaTeX Error: Something's wrong--perhaps a missing \item.
```

probably due to the fact that the following is rendered:

```
\begin{highlights}
\begin{itemize}
\item Highlight 1
\item Highlight 2
\item Highlight 3
\item Highlight 4
\end{itemize}
\end{highlights}
```

instead of:

```
\begin{highlights}
\item Highlight 1
\item Highlight 2
\item Highlight 3
\item Highlight 4
\end{highlights}
```

and the additional `itemize` environment is causing a problem.

**Comment by stevejpurves** [comment]
This is a possible solution https://github.com/executablebooks/mystjs/issues/313

**Comment by fwkoch** [comment]
This solution makes sense - doesn't seem realistic to change list rendering behaviour based on a `part` name.

I recall a previous time we wanted a list option and just did an option for each index, like `highlight_1`, `highlight_2` etc instead of `highlights` - this is only viable if the length of the list is constrained...

Another point to consider is that (for now) options will not be parsed (i.e. emphasis, subscript, etc will not be converted to latex), so these highlights must be plain text. We could always add parsing to these options though...
